### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by amitmawkin** [federomero/pretty-json#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [pretty-json](https://github.com/federomero/pretty-json) package, v0.3.2

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1443

RangeError: Maximum call stack size exceeded
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1443:17)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1421:12)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:360:27)
  at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:56:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:431:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:769:26)
  at prettify (/Users/cwl609/.atom/packages/pretty-json/index.coffee:8:12)
  at atom-workspace.atom.commands.add.pretty-json:prettify (/Users/cwl609/.atom/packages/pretty-json/index.coffee:35:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -7:58.6 editor:auto-indent (atom-text-editor.editor.is-focused)
     -7:36.7 autoflow:reflow-selection (atom-text-editor.editor.is-focused)
     -6:59.9 core:undo (atom-text-editor.editor.is-focused)
  5x -4:03.9 core:backspace (atom-text-editor.editor.mini)
     -3:58.4 core:paste (atom-text-editor.editor.mini)
  5x -3:48.6 core:backspace (atom-text-editor.editor.mini)
     -3:47.2 core:confirm (atom-text-editor.editor.mini)
     -3:31.9 core:paste (atom-text-editor.editor.mini)
     -3:25.8 core:backspace (atom-text-editor.editor.mini)
     -3:22.1 core:confirm (atom-text-editor.editor.mini)
  2x -3:12.8 core:backspace (atom-text-editor.editor.mini)
     -2:39.4 core:paste (atom-text-editor.editor.mini)
  2x -2:38.4 core:confirm (atom-text-editor.editor.mini)
  5x -2:32.1 core:backspace (atom-text-editor.editor.mini)
  2x -2:29.8 core:confirm (atom-text-editor.editor.mini)
     -0:07.7 pretty-json:prettify (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by lexicalunit** [comment]
@amitmawkin Do you have an example of the JSON you were trying to prettify when this problem occurred? If you can't post the JSON for privacy reasons, can you let me know if it was very large? Perhaps there's a limit to the size of JSON that can be processed at a time...

**Comment by amitmawkin** [comment]
not any more, will close this issue I reinstalled the product

**Comment by lexicalunit** [comment]
Glad you found a solution and thanks for getting back to me so quickly :+1:

**Comment by zmingxie** [comment]
Hmm... I just hit this when trying to prettify a 4MB JSON file. Should it be expected?

**Comment by lexicalunit** [comment]
It's possible there is an issue with the parsing & stringifying library that `pretty-json` uses. You might want to give atom-beautify a chance and see if it works for you.
