### ISSUE TITLE
Failed to load the pretty-json package

### ISSUE THREAD

**Issue by audiotech** [federomero/pretty-json#27]
[Enter steps to reproduce below:]

1. Happens on opening atom

**Atom Version**: 1.0.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [pretty-json](https://github.com/federomero/pretty-json) package, v0.4.1

### Stack Trace

Failed to load the pretty-json package

```
At Cannot find module 'json-stable-stringify'

Error: Cannot find module 'json-stable-stringify'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\paulk\.atom\packages\pretty-json-0.4.1\index.coffee:1:13)
  at Object.<anonymous> (C:\Users\paulk\.atom\packages\pretty-json-0.4.1\index.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:715:34)
  at C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:337:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\paulk\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/paulk/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/paulk/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-mustache",
      "autoflow",
      "autosave",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-property-list",
      "language-sass",
      "language-shellscript",
      "language-source",
      "language-todo",
      "language-toml",
      "language-yaml",
      "metrics",
      "settings-view",
      "jslint"
    ],
    "themes": [
      "isotope-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      "*.rti",
      "*.zip",
      "*.db",
      "*.bin",
      "*.cfg",
      "*.dat",
      "*.scc",
      ".project"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.29.0
isotope-ui, v2.0.1
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by Spiderbezno** [comment]
I have the same problem with Atom 1.2

**Comment by lexicalunit** [comment]
It appears that dependency `json-stable-stringify` did not get properly installed as this error is occurring when trying to load that package. There are a number of reasons why this might happen and unfortunately all of those are out of my control. I would suggest trying to uninstall and re-install the package. Or you could try and manually install the `json-stable-stringify` dependency by running `npm install` in the `pretty-json` package directory (in OS X that would be in `~/.atom/packages/pretty-json`).
