### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by magic890** [federomero/pretty-json#33]
[Enter steps to reproduce below:]

1. Select the content of a long JSON file
2. Packages -> Pretty JSON -> Prettify 

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:457

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:457:29)
    at TextBuffer.module.exports.TextBuffer.getEndPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:961:38)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1020:21)
    at MarkerLayer.module.exports.MarkerLayer.setMarkerRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:381:29)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:321:20)
    at Marker.module.exports.Marker.clearTail (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:187:19)
    at TextEditorMarker.module.exports.TextEditorMarker.clearTail (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:215:32)
    at Selection.module.exports.Selection.clear (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:193:21)
    at Cursor.module.exports.Cursor.clearSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:624:55)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:670:12)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1448:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1652:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1447:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:662:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
  5x -5:13.3.0 core:undo (atom-text-editor.editor.is-focused)
  4x -5:09.0 core:redo (atom-text-editor.editor.is-focused)
  4x -5:05.5.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:01.9.0 core:redo (atom-text-editor.editor.is-focused)
     -4:50.3.0 core:close (atom-text-editor.editor.is-focused)
  2x -4:49 core:undo (atom-text-editor.editor.is-focused)
     -4:44.2.0 core:redo (atom-text-editor.editor.is-focused)
     -4:07.6.0 tree-view:remove (span.name.icon.icon-file-text)
     -1:17.4.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:34.6.0 application:open (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24 editor:newline (atom-text-editor.editor.is-focused)
     -0:22 core:backspace (atom-text-editor.editor.is-focused)
     -0:18 core:select-all (atom-text-editor.editor.is-focused)
     -0:13.6.0 pretty-json:prettify (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.2.0
autoclose-html, v0.20.0
console-log, v0.9.3
file-icons, v1.6.14
language-hocon, v1.1.0
language-latex, v0.6.1
language-scala, v1.1.6
linter, v1.11.3
minimap, v4.19.0
pigments, v0.23.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by lexicalunit** [comment]
There have been a number of large refactors since this issue was reported and I can no longer reproduce this issue anymore. It may have been already solved. Please re-open if you continue to have this issue with the current release. Thanks for reporting it!
