### ISSUE TITLE
Uncaught Error: Cannot find module 'bignumber.js'

### ISSUE THREAD

**Issue by jmagana2000** [federomero/pretty-json#51]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [pretty-json](https://github.com/federomero/pretty-json) package, v1.4.2

### Stack Trace

Uncaught Error: Cannot find module 'bignumber.js'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

Error: Cannot find module 'bignumber.js'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.formatter.stringify (/Users/joshuamagana/.atom/packages/pretty-json/index.coffee:15:15)
    at Object.formatter.pretty (/Users/joshuamagana/.atom/packages/pretty-json/index.coffee:42:20)
    at /Users/joshuamagana/.atom/packages/pretty-json/index.coffee:89:48
    at /Users/joshuamagana/.atom/packages/pretty-json/index.coffee:82:36
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:874:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1328:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2224:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:866:19)
    at Object.PrettyJSON.replaceText (/Users/joshuamagana/.atom/packages/pretty-json/index.coffee:78:12)
    at Object.PrettyJSON.prettify (/Users/joshuamagana/.atom/packages/pretty-json/index.coffee:89:8)
    at atom-workspace.atom.commands.add.pretty-json:prettify (/Users/joshuamagana/.atom/packages/pretty-json/index.coffee:107:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
  2x -0:08.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.5.0 pretty-json:prettify (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
pretty-json, v1.4.2

# Dev
No dev packages
```

**Comment by lexicalunit** [comment]
My apologies for this issue! This should now be resolved in release version 1.4.4. Thank you for the ticket @jmagana2000 👍
